name: Count Files and Update README

on:
  push:
    branches:
      - main

jobs:
  count-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Count files and generate table
        id: count_files
        run: |
          count_file="file_counts.md"
          echo "| Main Folder | File Extension | Count |" > $count_file
          echo "|--------------|----------------|-------|" >> $count_file

          # Loop through directories and count files
          for dir in ./*; do
            if [ -d "$dir" ]; then
              main_folder=$(basename "$dir")
              # Count files by extension
              find "$dir" -type f ! -path "*/git/*" ! -path "*/github/*" | \
              awk -F. '{ if (NF>1) print $NF }' | sort | uniq -c | \
              awk -v folder="$main_folder" '{print "| " folder " | " $2 " | " $1 " |"}' >> $count_file
            fi
          done

      - name: Update README.md
        run: |
          # Append the generated table to README.md
          echo "## File Count" >> README.md
          cat file_counts.md >> README.md
          rm file_counts.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Update README.md with file count" || echo "No changes to commit"
          git push
